### ISSUE TITLE
get the Raspberry Pi into fastboot mode

### ISSUE THREAD

**Issue by yangfan01-spec** [raspberry-vanilla/android_local_manifest#109]
Hello,
I now hope to discover the Raspberry Pi device using fastboot devices. How can I get the Raspberry Pi into fastboot mode?

Currently, after executing adb devices in Windows PC, the Raspberry Pi device can be recognized. However, after executing fastboot devices,  the number of displayed devices is 0. Do you have any good suggestions?

If it were a phone, I could enter Fastboot by turning off the power and pressing the volume - and power buttons until the screen turns on. However, the Raspberry Pi doesn't have these buttons...

**Comment by KonstaT** [comment]
fastboot is a protocol used to interact with the device when booted to Android bootloader. Since Raspberry Pi is not an Android device to begin with, it doesn't have an Android bootloader (i.e. no fastboot).

You could look into implementing e.g. U-Boot but that is not currently in the scope of Raspberry Vanilla project.

**Comment by yangfan01-spec** [comment]
Thank you very much for your reply, it was very helpful to me!
I will try using U-Boot to solve my problem.

**Comment by yangfan01-spec** [comment]
I would appreciate your guidance on whether there is any method to execute 'adb remount' and gain root access to the /system folder without utilizing the bootloader. Thank you for your assistance.

**Comment by KonstaT** [comment]
https://github.com/raspberry-vanilla/android_local_manifest/issues/47#issuecomment-1829888921
