### ISSUE TITLE
Luminosity Control on Custom Android TV ROM 13 for Raspberry Pi 4

### ISSUE THREAD

**Issue by rania-taabouri** [raspberry-vanilla/android_local_manifest#122]
I am having trouble controlling the screen luminosity on my custom Android TV ROM 13 running on a Raspberry Pi 4. Unlike on my phone, where I can adjust luminosity freely, the Android TV ROM does not include a built-in toolbar or controls for adjusting brightness. Attempts to obtain a brightness control tool from APKPure have been unsuccessful.

**Comment by KonstaT** [comment]
Because it's an external display connected via HDMI. It's not technically possible (while I know DDC/CI exists).

**Comment by rania-taabouri** [comment]
it's the raspberrypi 7inch touch screen what if i switch the build to tablet or automotive will be possibel to control it through a notification bar

**Comment by KonstaT** [comment]
Yes, it works on regular tablet target given you've followed https://github.com/raspberry-vanilla/android_local_manifest/wiki/DSI-display to use the official Raspberry 7" DSI display.

Can't recall if Android Automotive has a brightness slider. Android TV does not because you generally can't adjust brightness on an external display.

**Comment by rania-taabouri** [comment]
is it possible to add a brightness slider on a the tv target or the automotive if it doesn't exist
