### ISSUE TITLE
Clarification regarding documentation

### ISSUE THREAD

**Issue by ArulGandhi** [raspberry-vanilla/android_local_manifest#130]
Just wanted to clarify as this is in the readme of this repo, which is under raspberry-vanilla:
Select the device (rpi4 or rpi5) and build target (tablet UI, tv for Android TV, or car for Android Automotive):
Can Android TV be built from AOSP? The readme states that we can "build" a specific UI for the OS and that is fine but there are no AOSP-TV builds on the website by @KonstaT . Simply requesting clarification. Would love to contribute to the documentation, making it easier to understand for beginner-intermediate devs like me.

**Comment by KonstaT** [comment]
Yes, Raspberry Vanilla project supports tablet UI, Android TV, and Android Automotive build targets for Raspberry Pi 4 & 5 as stated in the documentation.

As stated on my website, "Raspberry Pi hardware specific implementation in this build is based on source code released on my [Raspberry Vanilla](https://github.com/raspberry-vanilla) project but this build still offers various additional features and enhancements over that.". I have not released any AOSP Android TV nor Android Automotive builds since they don't offer much use outside development purposes.

**Comment by ArulGandhi** [comment]
Pardon me for not reading that part. Thanks for confirming
