### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by EpicKau** [raspberry-vanilla/android_local_manifest#26]
Hey guys,
thanks for this awesome guide. I build the r82 and its working fine :)
How is it possible to deploy the monthly security updates? Is there a smart way to only compile these and build a ota update? 
Thanks.

**Comment by KonstaT** [comment]
If you've followed the instructions (https://github.com/raspberry-vanilla/android_local_manifest/tree/android-13.0) you'd currently build AOSP android-13.0.0_r75 branch.

android-13.0.0_r75 translates to TQ3A.230901.001 which is the latest Android 13 release for various Pixel devices.
android-13.0.0_r82 is TQ3C.230901.001.B1 which is for Verizon variant of Pixel Fold.
https://android.googlesource.com/platform/build/
https://developers.google.com/android/images

Since Pixel devices have been updated to Android 14 in October there's no further Android 13 Pixel branches.

Further Android 13 security updates are released in android-security-13.0.0_rXX branches. If you want to use some other branch not specified in the build instructions, you'd also need to take care of maintaining the projects that are forked from AOSP:
https://github.com/raspberry-vanilla/android_build
https://github.com/raspberry-vanilla/android_build_soong
https://github.com/raspberry-vanilla/android_external_v4l2_codec2
https://github.com/raspberry-vanilla/android_packages_modules_Wifi
