### ISSUE TITLE
Issue with Evs_App 

### ISSUE THREAD

**Issue by SarbeenaS** [raspberry-vanilla/android_local_manifest#31]
Hi Konsta,
We switched to https://github.com/raspberry-vanilla/android_local_manifest/tree/android-13.0 branch and successfully created OS image and flashed to Raspberry Board. From there opened EvsCameraPreview App , and it launched with camera output from USB camera connected on the board as attached EvsCameraAppPreview.jpg -
![EvsCameraAppPreview](https://github.com/raspberry-vanilla/android_local_manifest/assets/144411781/6ec2e4b9-01e9-4d78-96e8-049e8e6bad36)

But while launching evs_app, facing segmentation fault. Below is the logs captured after connecting adb to the device.

|rpi4:/ # logcat | grep "EvsApp"
01-01 00:00:16.062 172 172 I EvsApp : Acquiring EVS Display
01-01 00:00:16.065 172 172 I EvsApp : Connecting to Vehicle HAL
01-01 00:00:16.070 172 172 I EvsApp : Constructing state controller
01-01 00:00:16.072 172 172 I EvsApp : Camera list callback received 6cameras.
01-01 00:00:16.072 172 172 W EvsApp : No config information for hardware camera /dev/video22
01-01 00:00:16.072 172 172 W EvsApp : No config information for hardware camera /dev/video21
01-01 00:00:16.072 172 172 W EvsApp : No config information for hardware camera /dev/video15
01-01 00:00:16.072 172 172 W EvsApp : No config information for hardware camera /dev/video14
01-01 00:00:16.072 172 172 W EvsApp : No config information for hardware camera group0
01-01 00:00:16.072 172 172 I EvsApp : Entering running state
01-01 00:00:16.542 172 442 I EvsApp : Activated state 4
10-26 12:05:22.128 2599 2599 I EvsApp : EVS app starting
10-26 12:05:22.130 2599 2599 I EvsApp : Acquiring EVS Enumerator
10-26 12:05:22.132 2599 2599 I EvsApp : Acquiring EVS Display
10-26 12:05:22.157 2599 2599 I EvsApp : Connecting to Vehicle HAL
10-26 12:05:22.166 2599 2599 I EvsApp : Constructing state controller
10-26 12:05:22.168 2599 2599 I EvsApp : Camera list callback received 6cameras.
10-26 12:05:22.168 2599 2599 W EvsApp : No config information for hardware camera /dev/video22
10-26 12:05:22.168 2599 2599 W EvsApp : No config information for hardware camera /dev/video21
10-26 12:05:22.168 2599 2599 W EvsApp : No config information for hardware camera /dev/video15
10-26 12:05:22.168 2599 2599 W EvsApp : No config information for hardware camera group0
10-26 12:05:22.168 2599 2599 W EvsApp : No config information for hardware camera /dev/video14
10-26 12:05:22.169 2599 2599 I EvsApp : Entering running state
10-26 12:05:22.224 2599 2603 I EvsApp : Activated state 4
10-26 12:08:15.425 2633 2633 I EvsApp : EVS app starting
10-26 12:08:15.426 2633 2633 I EvsApp : Acquiring EVS Enumerator
10-26 12:08:15.428 2633 2633 I EvsApp : Acquiring EVS Display
10-26 12:08:15.429 2633 2633 I EvsApp : Connecting to Vehicle HAL
10-26 12:08:15.433 2633 2633 I EvsApp : Constructing state controller
10-26 12:08:15.454 2633 2633 I EvsApp : Camera list callback received 6cameras.
10-26 12:08:15.454 2633 2633 W EvsApp : No config information for hardware camera /dev/video22
10-26 12:08:15.454 2633 2633 W EvsApp : No config information for hardware camera /dev/video21
10-26 12:08:15.454 2633 2633 W EvsApp : No config information for hardware camera /dev/video15
10-26 12:08:15.454 2633 2633 W EvsApp : No config information for hardware camera group0
10-26 12:08:15.454 2633 2633 W EvsApp : No config information for hardware camera /dev/video14
10-26 12:08:15.457 2633 2633 I EvsApp : Entering running state
10-26 12:08:15.552 2633 2637 I EvsApp : Activated state 4
10-26 12:09:03.553 2633 2633 W EvsApp : evs_app is being terminated on receiving a signal 2
10-26 12:09:03.555 2633 2637 W EvsApp : EvsStateControl update loop ending
10-26 12:09:03.555 2633 2637 E EvsApp : Shutting down app due to state control loop ending

Is these camera details should be filled to configuration files and to be uploaded to /system/etc/automotive/evs/ path ? And do config_override.json do need any other changes ?
Please provide your inputs for resolving this issue.

Thanks in advance,
Sarbeena

**Comment by KonstaT** [comment]
So, in other words, it's working as expected. I don't see anything segfaulting/crashing in the log or any issue otherwise.

evs_app is a system service that is already running - not something that you should be executing manually.
https://source.android.com/docs/automotive/camera-hal#evs-application-component
https://android.googlesource.com/platform/packages/services/Car/+/refs/tags/android-13.0.0_r75/cpp/evs/apps/default/evs_app.rc

Not all `/dev/video*` nodes are for camera devices. Some of these are for Pi's hw video decoder/encoder and camera ISP. External camera HAL has configs to ignore these devices (https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-13.0/camera/external_camera_config.xml#L21-L35) but I'm not aware there being similar configuration for the EVS camera HAL. It doesn't cause any issue either that EVS HAL tries to open the additional devices (as it's configured to use `/dev/video0` - https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-13.0/overlay/CarServiceRpiOverlay/res/values/config.xml#L29-L30).

AOSP only provides reference implementation for the EVS and a sample app. It's up to the OEM (i.e. in this case you) to build upon that.
https://source.android.com/docs/automotive/camera-hal
