### ISSUE TITLE
no raspberry pi settings in android automotive 14?

### ISSUE THREAD

**Issue by SuperPou1** [raspberry-vanilla/android_local_manifest#35]
I built aaos 14 and in settings > system there are no raspberry pi settings like there are on your prebuilt images. why is it?

**Comment by KonstaT** [comment]
Because it's not part of Raspberry Vanilla project. I'm not providing any prebuilt Android Automotive images either.

You can achieve the same result for most parts by following the documentation (https://github.com/raspberry-vanilla/android_local_manifest/wiki) or editing config.txt (GPIO buttons, CPU overclocking, etc).

**Comment by abhilashdeshmukh** [comment]
I am quite new to android builds, so what do you mean it is not part of Raspberry Vanilla project?  
I am guessing raspberry pi setting is not part of it, but does that means we can add it for AAOS build also? 
I actually want to reboot into recovery so that I can install Google Play, it will be great if you can help me for that.

**Comment by KonstaT** [comment]
It means exactly that, it's not part of Raspberry Vanilla project.

Recovery is also not part of Raspberry Vanilla project. You can look into e.g. https://github.com/twrp-raspberry on how to build TWRP for Raspberry Pi.

You don't need to have recovery to include GApps in your **personal** builds (see e.g. https://gitlab.com/MindTheGapps/vendor_gapps#build-inline-with-android). Note that you're not allowed to distribute any Android image with Google services without acquiring GMS licensing (https://www.android.com/gms/).

**Comment by abhilashdeshmukh** [comment]
Thank you for quick response, I will check it.
Yes, I am only using AAOS for personal use...

**Comment by ssrakesh** [comment]
thanks for the guide I was able to integrate and use gapps
