### ISSUE TITLE
Include rsync

### ISSUE THREAD

**Issue by Eskuero** [raspberry-vanilla/android_local_manifest#46]
Would it be possilbe to include an rsync binary?

On your LineageOS builds it's under /system/product/bin/rsync

I frequently dump data using the root user via SSH using rsync and it was really convenient to use.

**Comment by KonstaT** [comment]
Include in what exactly since Raspberry Vanilla doesn't have SSH either? There's no plans to include rsync in my personal AOSP builds.

You can likely just copy over the rsync binary (and any missing shared libraries - https://github.com/LineageOS/android_external_rsync/blob/lineage-20.0/Android.bp#L18-L23) from my LineageOS build over to AOSP build.

To include rsync in your own AOSP build, you would add https://github.com/LineageOS/android_external_rsync to the device manifest and in device.mk:
```
PRODUCT_PACKAGES += \
    rsync
```
