### ISSUE TITLE
OTA - failed to build package target files in AOSP13 RPI4

### ISSUE THREAD

**Issue by FeroVbee** [raspberry-vanilla/android_local_manifest#69]
I'm working on OTA for android. everything is going well to build AOSP13 and generate image to flash to RPI4. however, when I run the :

`make dist DIST_DIR=dist_output` (exactly what AOSP suggests)

I get the following error:
`Package target files: out/target/product/rpi4/obj/PACKAGING/target_files_intermediates/aosp_rpi4-target_files-eng.myproject.zip FAILED: out/target/product/rpi4/obj/PACKAGING/target_files_intermediates/aosp_rpi4-target_files-eng.myproject.zip /bin/bash -c ". . ." acp: missing destination file 19:54:32 ninja failed with: exit status 1`

This seems similar to his issue: https://stackoverflow.com/questions/77985724/acp-missing-destination-file-in-target-file-generation-for-ota-generation-using

Do you have a solution for that problem? so that I can create my own OTA package with your help.
Thanks,

**Comment by KonstaT** [comment]
Yes, OTA packages are not supported on Raspberry Vanilla project due to how the Android OS image is structured on Raspberry Pi.

First of all, you would need to build/add recovery image to be able to install the OTA package in the first place. This is also required for creating an OTA package among other hacks.
