### ISSUE TITLE
Rpi4 vlan ping not working

### ISSUE THREAD

**Issue by thangarajpvaleo** [raspberry-vanilla/android_local_manifest#78]
Issue:
     **Rpi4 vlan ping not working**
tried:
- enabled the kernel config [CONFIG_VLAN_8021Q=y]
- and able to create vlan on rpi4 android using ip add link command.
- when tried to ping another vlan ip on the network, it shows network unreachable. but normal ip ping works.
- please help to check and resolve the issue. @KonstaT 

steps followed:
- repo init -u https://android.googlesource.com/kernel/manifest -b common-android13-5.15-lts [repo init]
- curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi4.xml -O -L https://raw.githubusercontent.com/raspberry- 
  vanilla/android_kernel_manifest/android-13.0/manifest_brcm_rpi4.xml [kernel manifest]
- repo sync
- enabled the kernel config [CONFIG_VLAN_8021Q, CONFIG_VLAN_8021Q_GVRP=y, CONFIG_VLAN_8021Q_MVRP=y]
- BUILD_CONFIG=common/build.config.rpi4 build/build.sh [build kernel]
- kernel Image, dtbs, and overlays from out/common/arch/arm64/boot replaced in aosp-rpi4/device/brcm/rpi4-kernel/ 
- and flashed the aosp full image for rpi4.

**Comment by thangarajpvaleo** [comment]
- Do we need to enable/disbale any policy/ip table rules/etc., ?
- Or any kernel config needs to enabled additionally? 
@KonstaT

**Comment by KonstaT** [comment]
No idea TBH. Some documentation I found (https://trac.gateworks.com/wiki/linux/vlan) states that enabling `CONFIG_VLAN_8021Q` on kernel side should be enough. Make sure that you've modified the correct defconfig (i.e. https://github.com/raspberry-vanilla/android_kernel_brcm_rpi/blob/android-13.0/arch/arm64/configs/lineageos_rpi4_defconfig) to enable the driver.

Since AFAIK Android doesn't have anything to support VLAN in userspace, this is not in scope of Raspberry Vanilla project. Yes, you'd probably need some additional configuration on command line but Google search knows more than I do. I don't have any hardware to test in any case.
